export const albums = [
  { albumName: 'Showbiz', albumId: 'album1' },
  { albumName: 'Origin of Symmetry', albumId: 'album2' },
  { albumName: 'Absolution', albumId: 'album3' },
  { albumName: 'Black Holes And Revelations', albumId: 'album4' },
  { albumName: 'The Resistance', albumId: 'album5' },
  { albumName: 'The 2nd Law ', albumId: 'album6' },
  { albumName: 'Drones', albumId: 'album7' },
  { albumName: 'Simulation Theory', albumId: 'album8' },
  //Used for performance testing.
  // { albumName: 'Simulation Theory', albumId: 'album9' },
  // { albumName: 'Simulation Theory', albumId: 'album10' },
  // { albumName: 'Simulation Theory', albumId: 'album11' },
  // { albumName: 'Simulation Theory', albumId: 'album12' },
  // { albumName: 'Simulation Theory', albumId: 'album13' },
  // { albumName: 'Simulation Theory', albumId: 'album14' },
  // { albumName: 'Simulation Theory', albumId: 'album15' },
  // { albumName: 'Simulation Theory', albumId: 'album16' },
  // { albumName: 'Simulation Theory', albumId: 'album17' },
  // { albumName: 'Simulation Theory', albumId: 'album18' },
  // { albumName: 'Simulation Theory', albumId: 'album19' },
  // { albumName: 'Simulation Theory', albumId: 'album20' },
  // { albumName: 'Simulation Theory', albumId: 'album21' },
  // { albumName: 'Simulation Theory', albumId: 'album22' },
  // { albumName: 'Simulation Theory', albumId: 'album23' },
  // { albumName: 'Simulation Theory', albumId: 'album24' },
  // { albumName: 'Simulation Theory', albumId: 'album25' },
  // { albumName: 'Simulation Theory', albumId: 'album26' },
  // { albumName: 'Simulation Theory', albumId: 'album27' },
  // { albumName: 'Simulation Theory', albumId: 'album28' },
  // { albumName: 'Simulation Theory', albumId: 'album29' },
  // { albumName: 'Simulation Theory', albumId: 'album30' },
]
export const fields = [
  {
    fieldName: 'What is the general message of the album?',
    fieldId: 'feild1',
    fieldType: 'text',
  },
  { fieldName: 'What track stands out?', fieldId: 'feild2', fieldType: 'text' },
  { fieldName: 'What track pull the album down?', fieldId: 'feild3', fieldType: 'text' },
  { fieldName: 'How is the band evolving in this album?', fieldId: 'feild4', fieldType: 'text' },
  {
    fieldName: 'How does this compare to their other albums?',
    fieldId: 'feild5',
    fieldType: 'text',
  },
  {
    fieldName: 'What other bands or albums does this album remind you of?',
    fieldId: 'feild6',
    fieldType: 'text',
  },
  {
    fieldName: 'Overall Rating',
    fieldId: 'feild7',
    fieldType: 'radio',
    fieldOptions: ['1', '2', '3', '4', '5'],
  },
  //Used for performance testing
  // { fieldName: 'Final Notes', fieldId: 'feild8', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild9', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild10', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild11', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild12', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild13', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild14', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild15', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild16', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild17', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild18', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild19', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild20', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild21', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild22', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild23', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild24', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild25', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild26', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild27', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild28', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild29', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild30', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild31', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild32', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild33', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild34', fieldType: 'textarea' },
  // { fieldName: 'Final Notes', fieldId: 'feild35', fieldType: 'textarea' },
]
